# Generated by Django 4.1 on 2022-09-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "first_image",
                    models.ImageField(blank=True, null=True, upload_to="Images"),
                ),
                (
                    "second_image",
                    models.ImageField(blank=True, null=True, upload_to="Images"),
                ),
            ],
        ),
    ]
